version: '3'

volumes:
  dbdata:

services:
  api:
    image: backend-api
    build: .
    environment:
      NODE_ENV: development
      TYPEORM_HOST: db
      TYPEORM_DATABASE: backendapi_development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - db
    command: npm run dev

  db:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=backendapi_development
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
